### ISSUE TITLE
서비스 당위성 확인을 위한 설문조사 질문 작성

### ISSUE THREAD

**Issue by swoohooh** [swoohooh/carrot-digger#3]
**Describe `what` to do**
서비스 시작 전 설문조사를 통해 방향성 확인이 필요하고, 그를 위한 설문조사 질문 작성이 필요하다.

**Describe the expected outcome**
서비스 당위성 확인이 가능한 google form

**Describe `why` we need to do**
설문조사를 통해 다음을 알 수 있다.
- 기획의 당위성 및 방향성
- 소비자의 필요성

**Describe the expected `constraints` in doing this task**
답정너 설문이 되지 않도록 문구를 치우치지 않게 만들어야 한다.
구글에 검색해보니 좋은 설문 작성하기 많이 나옴

**Comment by hamzzi** [comment]
귀하의 성별은 어떻게 되시나요?
- 남
- 여

아기 옷을 한 달에 얼마나 구매하시나요?
- 1벌 이하
- 2 ~ 4벌
- 5벌 이상

아기 옷을 구매하시는데 한 달에 얼마나 사용하시나요?
- 1만원 이하
- 5만원 이하
- 10만원 이하
- 10만원 이상

아기 옷 대여 서비스를 이용하신다면 어떤 품목을 대여할 의향이 있으신가요
- 내복
- 외출복
- 외투
- 신발

아기 옷 대여 서비스를 이용하신다면 대여 기간은 얼마가 적당한가요
- 1주
- 2주
- 3주
- 4주
- 8주
- 12주

보유하고 있는 아기 옷은 몇벌 이신가요?
- 내복
- 외출복
- 외투
- 신발

아기 옷 중고 거래를 해보신 적이 있으신가요?
- 구매/판매 경험 있음
- 구매 경험 있음
- 판매 경험 있음
- 경험 없음

아이 옷 중고 거래를 하신 이유는 무엇인가요? (주관식)

**Comment by swoohooh** [comment]
귀하의 성별은 어떻게 되시나요?
- 남
- 여

자녀가 몇 명인가요? (주관식 입력)
- 남: X, 여: X

자녀들은 몇살 인가요? (다중선택)
- (@hamzzi 알려주심)

본인의 옷 구매를 위해 한달에 얼마를 사용하고 있으신가요?
- 1만원 이하
- 5만원 이하
- 10만원 이하
- 10만원 이상

아기 옷을 한 달에 얼마나 구매하시나요?
- 1벌 이하
- 2 ~ 4벌
- 5벌 이상

아기 옷 구매를 위해 한달에 얼마를 사용하고 있으신가요?
- 1만원 이하
- 5만원 이하
- 10만원 이하
- 10만원 이상

구매 한 자녀들의 옷은 평균적으로 얼마나 입을 수 있나요?
- 3달 이하
- 5달 이하
- 1년 이하
- 2년 이하
- 2년 이상

사이즈가 맞지 않는 옷은 어떻게 처리하시나요?
- 중고거래
- 의류 수거함
- 의류 기부, 기증
- 폐기
- 기타(주관식)

아기 옷 중고 거래를 해보신 적이 있으신가요?
- 구매/판매 경험 있음
- 구매 경험 있음
- 판매 경험 있음
- 경험 없음

아이 옷 중고 거래를 하신 이유는 무엇인가요? (주관식)

ESG 경영을 하는 기업들에 관심이 있나요?
- 네
- 아니오

아이 옷 구독 서비스가 존재한다면 사용하실 의향이 있나요?
- 네
- 아니오

아기 옷 구독 서비스를 이용하신다면 어떤 품목을 대여할 의향이 있으신가요?
- 내복
- 외출복
- 외투
- 신발

아기 옷 대여 서비스를 이용하신다면 대여 기간은 얼마가 적당한가요
- 1주
- 2주
- 3주
- 4주
- 8주
- 12주

대여 기간 동안 몇벌의 옷이 대여되길 희망하시나요? 
- 약 5개
- 약 10개
- 약 15개
- 약 30개
- 기타(주관식)

아이 옷 구독 서비스가 존재한다면 한 달에 얼마까지 지불하실 의향이 있나요?
- 3만원 이하
- 5만원 이하
- 7만원 이하
- 10만원 이하
- 기타(주관식)

보유하고 있는 아기 옷은 몇벌 이신가요?
- 내복
- 외출복
- 외투
- 신발


지불하신 금액으로 배달되길 기대하는 브랜드는 어떤 브랜드인가요? (다중선택)
- (네이버 브랜드 조사 후 입력)

**Comment by hamzzi** [comment]
![1688478792367](https://github.com/swoohooh/carrot-digger/assets/24203536/1ff1ce4e-c425-4ebc-953c-7027900d97e4)
사이즈 표에 맞는 나이로 하는게 좋을듯합니다

**Comment by swoohooh** [comment]
https://forms.gle/2SaqnWbCwqngkbbN8
@hamzzi 검토 후 의견 부탁드립니다. (특히 제목하고 설명 부분)

**Comment by hamzzi** [comment]
![Screenshot_20230712_080359_Samsung Internet](https://github.com/swoohooh/carrot-digger/assets/24203536/b0ff6677-8d03-4e06-8702-d8cc37d0ce21)

1. 중고거래를 한 이유
필수 질문이라 없으면 없다고 적으라고 알려주거나 필수 질문을 푸는게 좋을듯합니다.
2. ESG가 뭔지 적어주는게 좋을듯합니다

**Comment by hamzzi** [comment]
구독서비스를 이용할 의향이 있는경우/없는경우 사유를 들으면 좋을 것 같습니다

**Comment by hamzzi** [comment]
자녀들 나이에 0-12개월이 없네요

**Comment by swoohooh** [comment]
1. 중고거래를 한 이유
![image](https://github.com/swoohooh/carrot-digger/assets/58333547/0f3ce7dd-2745-4faa-a4e9-678c39a32927)

2. esg 
![image](https://github.com/swoohooh/carrot-digger/assets/58333547/06489aa5-fe00-47f2-8b3e-32fa2e9fbb05)

3. 이용 의향 
![image](https://github.com/swoohooh/carrot-digger/assets/58333547/175019ae-9454-4e0d-907a-5ce66478fdb9)

4. 자녀 나이
![image](https://github.com/swoohooh/carrot-digger/assets/58333547/66e7294b-4b89-4c24-8da4-794409ad8dbd)

**Comment by swoohooh** [comment]
아래의 문구 변경하고 싶은데 알려주세요 (@hamzzi )

![image](https://github.com/swoohooh/carrot-digger/assets/58333547/074bf24c-03ba-4f9e-99e2-13fe3a11724b)

**Comment by swoohooh** [comment]
완료
https://forms.gle/2SaqnWbCwqngkbbN8

**Comment by hamzzi** [comment]
https://docs.google.com/spreadsheets/d/1M6Ur4B1v8g1rwlD0XORpj-cZOOpdDEzvdnPCYSe0DxY/edit?usp=sharing
